# New-York City Taxi Data Analysis

In this mini-project we will do the useful analysis on the taxi data of New York city using Numpy

### Importing libraries

In [106]:
import numpy as np

### useful numpy functions

In [107]:
#converting scientific notations values in numpy array to normal values
np.set_printoptions(suppress=True)

### Converting CSV file to numpy array

In [108]:
taxi_data=np.genfromtxt(fname='nyc_taxis.csv',skip_header=True,delimiter=',')
print(taxi_data)

[[2016.     1.     1.  ...    5.5   11.7    1. ]
 [2016.     1.     1.  ...    0.     8.     1. ]
 [2016.     1.     1.  ...    0.     0.     2. ]
 ...
 [2016.     6.    30.  ...    5.5    5.     1. ]
 [2016.     6.    30.  ...    0.     8.9    1. ]
 [2016.     6.    30.  ...    5.5    0.     2. ]]


### shape of taxi_data

In [109]:
np.shape(taxi_data)

(89560, 14)

So, There are total 89560 rides in 2016

### Distance required to book a ride

##### Minimum distance required

In [110]:
distance_data=taxi_data[:,7:8]
print(f'Minimum distance:{np.min(distance_data)}')

Minimum distance:0.0


As we are getting minimum distance of 0.0 so we are removing 0.0 from our distance data 

In [111]:
print(f'total distances before:{len(distance_data)}')
new_distance_data=distance_data[distance_data!=0]
# print(new_distance_data)
print(f'total distance after:{len(new_distance_data)}')



total distances before:89560
total distance after:88829


Initially total number of rides were 89560 but after removing rides with 0.0 distance, number of rides are 88959

##### Minimum distance after removing 0.0

In [112]:
print(f'minimum distance:{np.min(new_distance_data)}')

minimum distance:0.1


##### Maximum distance 

In [113]:
print(f'Maximum distance:{np.max(distance_data)}')

Maximum distance:182.9


##### Average distance of rides

In [114]:
print(f'Average distance of rides:{np.mean(distance_data,dtype=int)}')

Average distance of rides:12


### Finding Speed of each rides

In [115]:
# print(distance_data)
# converting distance to metre
distance_metre=distance_data * 1000
# print(distance_data)
time_data=taxi_data[:,8:9]
# print(time_data)
speed=distance_metre/time_data
speed=np.round(speed,decimals=2)

### adding speed column to taxi data 

In [116]:
taxi_data=np.hstack((taxi_data,speed))
print(taxi_data)

[[2016.      1.      1.   ...   11.7     1.     10.31]
 [2016.      1.      1.   ...    8.      1.     10.72]
 [2016.      1.      1.   ...    0.      2.      8.69]
 ...
 [2016.      6.     30.   ...    5.      1.      6.2 ]
 [2016.      6.     30.   ...    8.9     1.     11.82]
 [2016.      6.     30.   ...    0.      2.     10.23]]


### converting array data to CSV/Excel

headers
pickup_year,pickup_month,pickup_day,pickup_dayofweek,pickup_time,pickup_location_code,dropoff_location_code,trip_distance,trip_length,fare_amount,fees_amount,tolls_amount,tip_amount,total_amount,payment_type


In [117]:
np.savetxt(fname='nyc_taxis.csv',
           X=taxi_data,
           delimiter=',',
           header='pickup_year,pickup_month,pickup_day,pickup_dayofweek,pickup_time,pickup_location_code,dropoff_location_code,trip_distance,trip_length,fare_amount,fees_amount,tolls_amount,tip_amount,payment_type,speed'
           ,fmt='%.1f')

### Finding total fare of each rides

In [125]:
fares=taxi_data[:,9:13]
total_fare=np.sum(fares,axis=1)
total_fare=np.reshape(total_fare,newshape=(89560,1))


### Add total fares column to data

In [126]:
taxi_data=np.hstack((taxi_data,total_fare))
print(taxi_data)

[[2016.      1.      1.   ...    1.     10.31   70.  ]
 [2016.      1.      1.   ...    1.     10.72   54.3 ]
 [2016.      1.      1.   ...    2.      8.69   37.8 ]
 ...
 [2016.      6.     30.   ...    1.      6.2    63.3 ]
 [2016.      6.     30.   ...    1.     11.82   44.7 ]
 [2016.      6.     30.   ...    2.     10.23   54.8 ]]


### converting Array to CSV/Excel

In [129]:
np.savetxt(fname='nyc_taxis.csv',
           X=taxi_data,
           delimiter=',',
           header='pickup_year,pickup_month,pickup_day,pickup_dayofweek,pickup_time,pickup_location_code,dropoff_location_code,trip_distance,trip_length,fare_amount,fees_amount,tolls_amount,tip_amount,payment_type,speed,total amount'
           ,fmt='%.1f')